version: '3.8'

services:

  rabbitmq:
    image: rabbitmq:3-management
    
    container_name: 'rabbitmq'

    networks:
      - backend_network

    ports:
      - '5672:5672'
      - '15672:15672'

    command: rabbitmq-server
  
  mongo:
    build:
      context: ./mongo_db
      dockerfile: Dockerfile

    container_name: 'mongodb'

    networks:
      - backend_network

    restart: always

    ports:
      - '27017:27017'
  
  backend:
    depends_on:
      - rabbitmq
      - mongo

    build: 
      context: ./MSH-backend
      dockerfile: Dockerfile

    container_name: 'msh_backend'

    volumes:
      - ./MSH-backend:/msh-backend

    networks:
      - backend_network
      - frontend_network

    ports:
      - '8080:8080'

  frontend:
    depends_on:
      - backend

    build: 
      context: ./MSH-frontend
      dockerfile: Dockerfile

    container_name: 'msh_frontend'

    networks:
      - frontend_network

    volumes:
      - ./MSH-frontend:/app
      - /app/node_modules

    ports:
      - '80:80'


  
networks:
  frontend_network:
    driver: bridge

  backend_network:
    driver: bridge
